### PR TITLE
First steps to improve modal dialog.

### PR DESCRIPTION
**Pull request by kegor**
**Problem:**

> Instead of hardcode dialog size, it must fit the content. Also, it must be centered independently of its size.
> 
> Note:
> - use flex positioning to solve centering
> - make sure that it works correctly in the mobile version as well
> - make sure it displays correctly in other products (Viewer)

**Solution:**
- was added flex positioning to solve centering
- markup of the modal dialog was rewritten

**Screenshots:**
browse_file_dialog

image

save_dialog

image

success_dialog

error_dialog

### CODE REVIEW

**Comment by kegor** [comment]
**Question:**
Should i try to rework the markup of the drag'n'drop area/control for uploading by url within this PR, wdyt?
Maybe you have suggestions regarding the current and future changes?

**Comment by kegor** [comment]
Few more changes were added. Mostly they are related to the success and password-requred modals. New screenshots were added as well. The main question can we go forward with such presentation or it significantly differs with the design?

**Comment by kegor** [comment]
@egorovpavel, @Pavel-Teplitsky i have changed few lines of `less` code to make success modal dialog more square and aligned to center, related screen-cast was added in the PR description as well, please take a look when you'll find time.

**Comment by Pavel-Teplitsky** [comment]
@kegor When number of files is bigger than one scroll the grey background isn't fit a list of files height http://prntscr.com/oc1ari

**Pull request merged**
